### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mml1** [harrison-bergeron/colmar-academy#3]
[Exceeds Expectations] Great work! You did a fantastic job with the following:

- descriptive comments
- descriptive labels for class/ids
- relative links to images
- relative links to stylesheet
- consistent indentation
- easy to navigate project structure
- div usage
- alt tag usage
- responsive design
- media query usage
- flexbox usage
- rem/em usage
- ordering your styles

In terms of improvement, try playing around with git/github and making a few git commits while building your project. 

Keep up the great work!

**Comment by harrison-bergeron** [comment]
Appreciate all the feedback!
